# Generated by Django 2.2.3 on 2019-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='tokens/token.png')),
                ('algorithm', models.TextField(default='')),
                ('r', models.IntegerField()),
                ('c', models.IntegerField()),
                ('coverage', models.IntegerField(default=1)),
                ('sight', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('active', models.BooleanField()),
                ('game_id', models.IntegerField(default=-1)),
                ('all_game_ids', models.TextField(default='')),
            ],
        ),
    ]
