# Generated by Django 2.2.3 on 2019-07-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='all_game_ids',
            field=models.TextField(default=''),
        ),
    ]
