# Generated by Django 2.2.3 on 2019-07-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='memory',
            field=models.TextField(default='[]'),
        ),
    ]
