# Generated by Django 2.2.3 on 2019-07-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_agent_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='movement',
            field=models.IntegerField(default=1),
        ),
    ]
