# Generated by Django 2.2.3 on 2019-08-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEvalSurveyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.IntegerField(default=-1)),
                ('confusion', models.IntegerField(default=-1)),
                ('collaboration', models.IntegerField(default=-1)),
                ('contribution', models.IntegerField(default=-1)),
                ('interaction', models.IntegerField(default=-1)),
                ('isolation', models.IntegerField(default=-1)),
                ('activity', models.IntegerField(default=-1)),
                ('understanding', models.IntegerField(default=-1)),
                ('intelligence', models.IntegerField(default=-1)),
                ('game_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
