# Generated by Django 2.2.3 on 2019-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsurvey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamevalsurveydata',
            name='difficulty',
            field=models.IntegerField(default=-1),
        ),
    ]
