# Generated by Django 2.2.3 on 2019-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('history', models.TextField(default='[]')),
                ('pending', models.TextField(default='{}')),
                ('agents', models.TextField(default='{}')),
                ('name', models.TextField(default='')),
                ('needs_refresh', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing', models.BooleanField(default=False)),
                ('AI_players', models.TextField(default='')),
                ('human_players', models.TextField(default='[]')),
                ('map_recipe', models.TextField(default='')),
                ('board_id', models.IntegerField(default=-1)),
                ('position_assignment', models.TextField(default='[]')),
            ],
        ),
    ]
