# Generated by Django 2.2.3 on 2019-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='snapshot_interval',
            field=models.IntegerField(default=10),
        ),
    ]
