# Generated by Django 2.2.3 on 2019-08-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='settings',
            field=models.TextField(default='{"coverage": 1, "sight": 3, "movement": 1, "map_knowledge":"false"}'),
        ),
    ]
