# Generated by Django 2.2.3 on 2019-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='score_history',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='board',
            name='needs_refresh',
            field=models.TextField(default='{"admin":true}'),
        ),
    ]
