# Generated by Django 2.2.3 on 2019-07-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_config_snapshot_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='AI_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='human_players',
        ),
    ]
