# Generated by Django 2.2.3 on 2019-08-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190801_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='optimal_score',
            field=models.IntegerField(default=0),
        ),
    ]
