# Generated by Django 2.2.3 on 2019-07-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190718_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
