# Generated by Django 2.2.3 on 2019-07-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
