# Generated by Django 2.2.3 on 2019-07-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190725_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='human_players',
            field=models.TextField(default='[]'),
        ),
    ]
