# Generated by Django 2.2.3 on 2019-09-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_board_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='assigner',
            field=models.TextField(default='{}'),
        ),
    ]
