# Generated by Django 2.2.3 on 2019-07-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_board_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('players', models.TextField(default='[]', null=True)),
                ('data', models.TextField(default='[]', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='needs_refresh',
            field=models.TextField(default='{"admin":"True"}'),
        ),
    ]
