# Generated by Django 2.2.3 on 2019-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190721_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='seq_data',
            field=models.TextField(default='', null=True),
        ),
    ]
