# Generated by Django 2.2.3 on 2019-07-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190721_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='seq_data',
            field=models.TextField(default='{}', null=True),
        ),
    ]
