# Generated by Django 2.2.3 on 2019-10-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190909_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='lastclick',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='config',
            name='snapshot_interval',
            field=models.IntegerField(default=1),
        ),
    ]
